spring:

  jpa:
    hibernate:
      ddlAuto: validate
    showSql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: amigo
    password: amigo

  flyway:
    baselineOnMigrate: true

